version: 2

formats:
  - htmlzip

build:
  os: ubuntu-20.04
  tools:
    python: 3.8

python:
  version: "3.8"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true

sphinx:
  builder: html
  configuration: docs/conf.py
#  fail_on_warning: true
